source 'https://rubygems.org'
gem 'cinch', git: 'git://github.com/cinchrb/cinch.git'
gem 'cinch-forecast'
gem 'cinch-wikipedia'
gem 'cinch-calculate'
gem 'cinch-weatherman'
gem 'weather-underground'
gem 'cinch-convert'
gem 'cinch-quotes'

gem 'chronic'
gem 'chronic_duration'
gem 'tag_formatter'
gem 'geocoder'
gem 'httparty'
gem 'nokogiri'

gem 'mongoid'
gem 'dotenv'
gem 'require_all'
gem 'redis'


gem 'sinatra'
gem 'async_sinatra'
gem 'haml'
gem 'sinatra-twitter-bootstrap', :require => 'sinatra/twitter-bootstrap'
