source 'https://rubygems.org'
gem 'nokogiri'

gem 'cinch', git: 'git://github.com/cinchrb/cinch.git'
gem 'cinch-forecast'
gem 'cinch-wikipedia'
gem 'cinch-calculate'
gem 'cinch-urbandictionary'
gem 'weather-underground'
gem 'cinch-convert'
gem 'cinch-quotes'

gem 'chronic'
gem 'chronic_duration'
gem 'tag_formatter'
gem 'geocoder'
gem 'httparty'

gem 'activerecord'
gem 'pg'
gem 'dotenv'
gem 'mkfifo'
gem 'god'

gem 'haml'
