source 'https://rubygems.org'
gem 'nokogiri'

gem 'cinch', git: 'git://github.com/cinchrb/cinch.git'
gem 'cinch-wikipedia'
gem 'cinch-calculate'
gem 'cinch-urbandictionary'
gem 'weather-underground'
gem 'cinch-quotes'

gem 'wolfram'
gem 'wolfram-alpha'
gem 'github_api'

gem 'chronic'
gem 'chronic_duration'
gem 'tag_formatter'
gem 'geocoder'
gem 'httparty'

gem 'sequel'
gem 'pg'
gem 'dotenv'
gem 'mkfifo'
gem 'god'
gem 'activesupport'

gem 'haml'
gem 'recursive-open-struct'
gem 'require_all'
