# Gems
require 'cinch/plugins/quotes'
require 'cinch-convert'
require 'cinch-calculate'
require 'cinch-wikipedia'
require 'weather-underground'

# Plugins in directory
require_relative '../plugins/8ball'
require_relative '../plugins/attack'
require_relative '../plugins/botinfo'
require_relative '../plugins/dice'
require_relative '../plugins/discord'
require_relative '../plugins/jargonfile'
require_relative '../plugins/link_info'
require_relative '../plugins/macros'
require_relative '../plugins/porno'
require_relative '../plugins/rainbow'
require_relative '../plugins/russian_roulette'
require_relative '../plugins/silly'
require_relative '../plugins/tell'
require_relative '../plugins/urbandictionary'
require_relative '../plugins/register'
require_relative '../plugins/vote'
require_relative '../plugins/weather'