module Admin; end
require 'Zeta/admin/channels'
require 'Zeta/admin/eval'
require 'Zeta/admin/fifo'
require 'Zeta/admin/oper'
require 'Zeta/admin/plugins'
require 'Zeta/admin/users'
require 'Zeta/admin/autojoin'
require 'Zeta/admin/ignore'
require 'Zeta/admin/bot'
require 'Zeta/admin/blacklister'