# Plugin Locale's
locale: en

# Bot
bot:
  nick: zeta
  nicks: 'zeta,crom'
  username: zeta
  realname: zeta

  # Auth Types are Channel/DB/BOTH
  auth:
    type: db
    channel: nil

  # Master Block
  master:
    nickname: you
    password: 'youneedthis'
    hostmask: 'you!you@you.com' # not used currently

# Database
db: 'sqlite://db/zeta.db'

# Server Block
server:
  # bot channel
  channels: '#bots'
  network: darkscience
  hostname: indigo.darkscience.net
#  hostname: irc.flagrun.net
  password:
  port: 6697
  ssl: true
  modes: '+B'
  max_messages: 10
  messages_per_second: 4.0

  services:
    chanserv: true
    nickserv: true
    memoserv: true
    rpgserv:  false
    botserv:  true
    hostserv: true
    operserv: true

  sasl:
    username:
    password:

  oper:
    username:
    password:


